# fly.toml app configuration file generated for olzhaschat on 2024-03-09T12:58:45+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'olzhaschat'
primary_region = 'waw'

[build]
  [build.args]
    GO_VERSION = '1.22'

[env]
  PORT = '8080'
  CORS_ORIGIN = 'https://chat.olzhasar.com'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[ metrics ]]
port = 2112
path = "/"
